#!/usr/bin/env python3

from textual.app import App, ComposeResult
from textual.containers import Horizontal
from textual.widgets import Footer, Header, Label, Placeholder, DirectoryTree
BANNER_ART =  r"""_      ____  _  __ _____ ____  ____  ____ 
/ \__/|/  _ \/ |/ //  __//  __\/  __\/  _ \
| |\/||| / \||   / |  \  |  \/||  \/|| / \|
| |  ||| |-|||   \ |  /_ |  __/|    /| \_/|
\_/  \|\_/ \|\_|\_\\____\\_/   \_/\_\\____/ 
"""
                                           

      

class Box(Placeholder):
	CSS_PATH = "makepro.css"
class Makepro(App):

	BINDINGS=[("d", "toggle_dark_mode", "Toggle Dark Mode")]
	CSS_PATH = "makepro.css"
	def compose(self) -> ComposeResult:
		yield Header(show_clock=True)
		yield Footer()
		dt=DirectoryTree("./")
		lbl =Label(BANNER_ART, id="title", markup=False)
		dt.border_title = "File Explorer"
		with Horizontal():
			yield dt
			yield lbl
	





	def action_toggle_dark_mode(self) -> None:
		self.theme = (
			"textual-dark" if self.theme == "textual-light" else "textual-light"
		)


if __name__ == "__main__":
	Makepro().run()
