#!/usr/bin/env python3
""" The sys module in Python provides access to system-specific parameters and functions that allow a program to interact closely with the Python interpreter and its runtime environment."""
import sys
from utils.textstyle import TextStyle

VERSION = "0.0.1"

if "--version" in sys.argv:
	print("makepro " + VERSION)
	sys.exit(0)

if "--help" in sys.argv:
	print(f"""usage : makepro <options>

OPTIONS :
	--version : Shows the program version
	--help : Shows the dialogue""")
	sys.exit(0)


try:
	from textual.app import App, ComposeResult
	from textual.containers import Horizontal, Vertical
	from textual.widgets import Footer, Header, Label, DirectoryTree, Button


except ModuleNotFoundError as e:
	print(f"""{TextStyle.bred('[ERROR]')} A {TextStyle.yellow('required Python module was not found')}: {TextStyle.cyan(e.name)}

                {TextStyle.yellow('This tool requires the + {e.name} +  package to be installed.')}

                {TextStyle.blue('Please try the following steps to resolve this issue:')}
		*   **Verify installation:** Ensure the package is installed in your current environment using `pip list`.
		*   **Install the package:** Run the following command to install the missing package:
			`pip install {e.name}`
			*   **Check environment:** If you are using a virtual environment, make sure it is activated and you are using the correct Python interpreter for installation and execution.
			*   **Double-check speling:** Python is case-sensitive. Verify the module name is spelled correctly.

                If the problem persists, please consult the tool's documentation or report an issue on the project's issue tracker.   m""")
	sys.exit(1)



except ImportError as e:
	print(f"""{TextStyle.bred('[ERROR]')} An {TextStyle.yellow('import error occurred')}: {e}

    {TextStyle.blue('Please try the following steps to resolve this issue:')}

    * **Verify installation:** Ensure the package installed in your current environment using 'pip list'.

    * **Install the package:** If you are using a virtual environent, make sure it is activated and you are using the correct python intrepreter for installation and execution.

    If the problem persists, please consult the tool's documentation or report an issue on the project's issue tracker.

       """)
	sys.exit(1)


BANNER_ART =  r"""_      ____  _  __ _____ ____  ____  ____ 
/ \__/|/  _ \/ |/ //  __//  __\/  __\/  _ \
| |\/||| / \||   / |  \  |  \/||  \/|| / \|
| |  ||| |-|||   \ |  /_ |  __/|    /| \_/|
\_/  \|\_/ \|\_|\_\\____\\_/   \_/\_\\____/ 
"""


class Makepro(App):

	CSS_PATH = "makepro.css"

	def compose(self) -> ComposeResult:
		yield Header(show_clock=True)
		yield Footer()
		fileexplorer = DirectoryTree("/")
		title = Label(
                BANNER_ART if self.app.size.width >= 30 else "Makepro",
                id="title",
                markup=False)
		newfile = Button("New File", variant="primary", classes="welcome_buttons")
		open = Button("Open File", variant="primary", classes="welcome_buttons")
		setting = Button("Settings", variant="primary", classes="welcome_buttons")
		donate = Button("Donate Us", variant="primary", classes="welcome_buttons")
		fileexplorer.border_title = "File Explorer"
		title.border_subtitle = f"v{VERSION} - Made by noirAnayCO"
		
		with Horizontal():
			yield fileexplorer
			
			with Vertical(classes="right-pane"):
				yield title
				
				with Horizontal(classes="button-row"):
					with Vertical(id="main-buttons"):
						yield newfile
						yield open

					with Vertical(classes="button-row"):
						yield donate
						yield setting
					



if __name__ == "__main__":
	Makepro().run()
