name: Makepro CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set PYTHONPATH for src layout
        run: echo "PYTHONPATH=src" >> $GITHUB_ENV

      - name: Syntax check
        run: python -m compileall src

      - name: Import test
        run: python -c "import makepro"